### ISSUE TITLE
Cannot find module 'tailwindcss-children'

### ISSUE THREAD

**Issue by tonyYo00** [SamGoody/tailwind-children#4] opened 2022-04-07 10:25 UTC
Cannot find module 'tailwindcss-children' in next.js

**Comment by SamGoody** [comment] 2022-04-12 09:16
I am guessing that this related to the fact fact that the ES6 module dynamically links the commonjsmoule, which is the same issue as #1 

There are three solutions I can think of: 

1. Compile for cjs on each release instead of linking it. I will probably do this.
2. Someone who knows next or vite can tell me how to use them :)

Am merging this into the other issue. Have been extremely busy in work the past few weeks, but will hopefully have another release soon solving this and the other issue.

**Comment by SamGoody** [comment] 2022-04-15 09:29
@tonyYo00 I have pushed a change that _should_ fix this, but don't know how to test.

Can you test and let me know how it goes?

**Comment by SamGoody** [comment] 2022-04-28 09:48
The issue is that the package is called `tailwind-children`, not `tailwind`**css**`-children`.

The documentation was wrong, and kudos to @ericpedia for picking it up.

Have updated the docs, and will close the issue. But thanks for pointing it out.

**Closed as completed by SamGoody** 2022-04-28 09:48 UTC
Labels: duplicate
